### ISSUE TITLE
Bug with caching of credentials

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-restful-api#56]
Currently when someone logs in with incorrect credentials, the login is cached and we are locked out. This is a bug that needs investigation and fixing. Pinging @khoing0810 who has expressed interest in working on it!

**Comment by khoing0810** [comment]
I made a PR.

Identified the issue being that the HTTP Basic Auth is not a cookie and, hence, is handled by the browser. I just had to switch the HTTPException status code from 400 to 401 and switched the Authorization header so the pop up will reappear whenever a user enter incorrect credetials. Future work include implementing logout mechanism (should behave the same way since HTTP Basic Auth doesn't have logout mechanism by design), but this should be a separate issue

**Comment by vsoch** [comment]
Great! So just to clarify, when a user either does not provide or provides incorrect credentials, we are returning a 401 response that is requesting them. Usually for command line clients after they have provided incorrect credentials you would return 400 (it’s a “denied - these were wrong”) but if you are saying here the different code fixes the bug, I’m happy to merge that!

**Comment by khoing0810** [comment]
Yes. We return 401 for unauthorized attempt and give it a chance for a user to fix their HTTP creds. I think 400 implicitly tells the user to change their creds but provided no form to let them do so. I think this one is a good source for when to choose what based on someone working on jwt-auth https://github.com/tymondesigns/jwt-auth/issues/1024

**Comment by vsoch** [comment]
Fixed by #57
